name: weather
description: Telegram bot that provides weather to the Coop chat

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dotenv: ^4.0.1
  teledart: ^0.5.4
  html: ^0.15.0
  debounce_throttle: ^2.0.0
  crypto: ^3.0.2
  nyxx: ^4.4.0
  nyxx_commands: ^4.3.0
  cron: ^0.5.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
