name: weather
description: Multi-platform bot that provides weather to the Coop chat plus some extra things
version: 3.18.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  teledart: ^0.6.1
  html: ^0.15.0
  debounce_throttle: ^2.0.0
  crypto: ^3.0.2
  nyxx: ^6.0.3
  nyxx_commands: ^6.0.1
  cron: ^0.5.1
  args: ^2.4.0
  http: ^1.1.1
  collection: ^1.17.1
  postgres: ^3.0.1
  meta: ^1.11.0
  uuid: ^4.2.1
  event_bus: ^2.0.0
  injectable: ^2.4.0
  get_it: ^7.6.7
  logger: ^2.0.2+1

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.8
  docker_process: ^1.3.1
  injectable_generator: ^2.6.1
  lints: ^3.0.0
  path: ^1.8.3
  test: ^1.6.0

dependency_overrides:
  analyzer: ^6.3.0
  nyxx:
    git:
      url: https://github.com/abitofevrything/nyxx.git
      ref: patch/hang-status
