name: weather
description: Telegram bot that provides weather to the Coop chat

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  dotenv: ^4.0.1
  teledart: ^0.3.4
  html: ^0.15.0
  debounce_throttle: ^2.0.0
  crypto: ^3.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
